---
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5

- name: Reload all conf files
  service:
    name: "{{ postgresql_daemon }}"
    state: reloaded

